/*!
 * chai
 * http://chaijs.com
 * Copyright(c) 2011-2014 Jake Luer <jake@alogicalparadox.com>
 * MIT Licensed
 */

import {AssertionError} from 'assertion-error';
import type {AssertionArgs, AssertionStatic, Message} from '../types.js';
import {config} from './config.js';
import * as util from './utils/index.js';

// export type {Assertion} from '../types.js';

export class Assertion {
  /** @type {{}} */
  __flags: {[key: PropertyKey]: unknown} = {};

  /**
   * Creates object for chaining.
   * `Assertion` objects contain metadata in the form of flags. Three flags can
   * be assigned during instantiation by passing arguments to this constructor:
   *
   * - `object`: This flag contains the target of the assertion. For example, in
   * the assertion `expect(numKittens).to.equal(7);`, the `object` flag will
   * contain `numKittens` so that the `equal` assertion can reference it when
   * needed.
   *
   * - `message`: This flag contains an optional custom error message to be
   * prepended to the error message that's generated by the assertion when it
   * fails.
   *
   * - `ssfi`: This flag stands for "start stack function indicator". It
   * contains a function reference that serves as the starting point for
   * removing frames from the stack trace of the error that's created by the
   * assertion when it fails. The goal is to provide a cleaner stack trace to
   * end users by removing Chai's internal functions. Note that it only works
   * in environments that support `Error.captureStackTrace`, and only when
   * `config.includeStack` hasn't been set to `false`.
   *
   * - `lockSsfi`: This flag controls whether or not the given `ssfi` flag
   * should retain its current value, even as assertions are chained off of
   * this object. This is usually set to `true` when creating a new assertion
   * from within another assertion. It's also temporarily set to `true` before
   * an overwritten assertion gets called by the overwriting assertion.
   *
   * - `eql`: This flag contains the deepEqual function to be used by the assertion.
   *
   * @param {unknown} target target of the assertion
   * @param {string} [message] (optional) custom error message
   * @param {Function} [ssfi] (optional) starting point for removing stack frames
   * @param {boolean} [lockSsfi] (optional) whether or not the ssfi flag is locked
   */
  constructor(
    target?: unknown,
    message?: string,
    ssfi?: (...args: any[]) => any,
    lockSsfi?: boolean
  ) {
    util.flag(this, 'ssfi', ssfi || Assertion);
    util.flag(this, 'lockSsfi', lockSsfi);
    util.flag(this, 'object', target);
    util.flag(this, 'message', message);
    util.flag(this, 'eql', config.deepEqual || util.eql);

    return util.proxify(this);
  }

  /** @returns {boolean} */
  static get includeStack(): boolean {
    console.warn(
      'Assertion.includeStack is deprecated, use chai.config.includeStack instead.'
    );
    return config.includeStack;
  }

  /** @param {boolean} value */
  static set includeStack(value: boolean) {
    console.warn(
      'Assertion.includeStack is deprecated, use chai.config.includeStack instead.'
    );
    config.includeStack = value;
  }

  /** @returns {boolean} */
  static get showDiff(): boolean {
    console.warn(
      'Assertion.showDiff is deprecated, use chai.config.showDiff instead.'
    );
    return config.showDiff;
  }

  /** @param {boolean} value */
  static set showDiff(value: boolean) {
    console.warn(
      'Assertion.showDiff is deprecated, use chai.config.showDiff instead.'
    );
    config.showDiff = value;
  }

  /**
   * @param {string} name
   * @param {Function} getter
   */
  static addProperty(
    name: string,
    getter?: (this: AssertionStatic) => any
  ): void {
    util.addProperty(this.prototype, name, getter);
  }

  /**
   * @param {string} name
   * @param {Function} method
   */
  static addMethod(
    name: string,
    method: (this: AssertionStatic, ...args: any[]) => any
  ) {
    util.addMethod(this.prototype, name, method);
  }

  /**
   * @param {string} name
   * @param {Function} method
   * @param {Function} chainingBehavior
   */
  static addChainableMethod(
    name: string,
    method: (this: AssertionStatic, ...args: any[]) => void,
    chainingBehavior?: () => void
  ) {
    util.addChainableMethod(this.prototype, name, method, chainingBehavior);
  }

  /**
   * @param {string} name
   * @param {Function} fn
   */
  static overwriteProperty(name: string, fn: (...args: any[]) => any) {
    util.overwriteProperty(this.prototype, name, fn);
  }

  /**
   * @param {string} name
   * @param {Function} method
   */
  static overwriteMethod(
    name: string,
    method: (this: AssertionStatic, ...args: any[]) => any
  ) {
    util.overwriteMethod(this.prototype, name, method);
  }

  /**
   * @param {string} name
   * @param {Function} method
   * @param {Function} chainingBehavior
   */
  static overwriteChainableMethod(
    name: string,
    method: (this: AssertionStatic, ...args: any[]) => void,
    chainingBehavior?: () => void
  ) {
    util.overwriteChainableMethod(
      this.prototype,
      name,
      method,
      chainingBehavior
    );
  }

  /**
   * ### .assert(expression, message, negateMessage, expected, actual, showDiff)
   *
   * Executes an expression and check expectations. Throws AssertionError for reporting if test doesn't pass.
   *
   * @name assert
   * @param {unknown} _expr to be tested
   * @param {string | Function} msg or function that returns message to display if expression fails
   * @param {string | Function} _negateMsg or function that returns negatedMessage to display if negated expression fails
   * @param {unknown} expected value (remember to check for negation)
   * @param {unknown} _actual (optional) will default to `this.obj`
   * @param {boolean} showDiff (optional) when set to `true`, assert will display a diff in addition to the message if expression fails
   * @returns {void}
   */
  assert(
    _expr: unknown,
    msg: Message,
    _negateMsg: Message,
    expected?: unknown,
    _actual?: unknown,
    showDiff?: boolean
  ): void {
    const args = arguments as unknown as AssertionArgs;
    const ok = util.test(this, args);
    if (false !== showDiff) showDiff = true;
    if (undefined === expected && undefined === _actual) showDiff = false;
    if (true !== config.showDiff) showDiff = false;

    if (!ok) {
      msg = util.getMessage(this, args);
      const actual = util.getActual(this, args);

      const assertionErrorObjectProperties = {
        actual,
        expected,
        showDiff
      } satisfies Record<PropertyKey, unknown> as Record<PropertyKey, unknown>;

      const operator = util.getOperator(this, args);
      if (operator) {
        assertionErrorObjectProperties.operator = operator;
      }

      throw new AssertionError(
        msg,
        assertionErrorObjectProperties,
        config.includeStack ? this.assert : util.flag(this, 'ssfi')
      );
    }
  }

  /**
   * Quick reference to stored `actual` value for plugin developers.
   *
   * @returns {unknown}
   */
  get _obj(): unknown {
    return util.flag(this, 'object');
  }

  /**
   * Quick reference to stored `actual` value for plugin developers.
   *
   * @param {unknown} val
   */
  set _obj(val: unknown) {
    util.flag(this, 'object', val);
  }
}
